spring:
  application:
    name: Config-Dev
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true # by default -- true
    register-with-eureka: true # by default -- true
    service-url:
      defaultZone: http://localhost:8761/eureka
